### ISSUE TITLE
MVP & Schema Design Docs Review

### ISSUE THREAD

**Issue by rlim92** [dblonc/Dancourt#1]
Hey Daniel! Design docs looking good, some suggestions below: 

### MVP
- [ ] The `dashboard` MVP we can think of as part of the end of `User Auth` where we get the landing page after logging in
- [ ] Split up MVPs in this way:
1. Servers
2. Channels within servers
3. Live Chat
4. Direct Messaging via private servers
- bullet points in MVPs look good!

### Schema
- [ ] This might be an older version of your schema, all 3 tables are the same. Refactor and let me know when you're ready!

Great work!

**Comment by dblonc** [comment]
Ah I didn't know what happened to my schema! Clipboard problem perhaps. Edited! 
On Thursday, March 11, 2021 Rich Lim ***@***.***> wrote:



Hey Daniel! Design docs looking good, some suggestions below:

MVP
   
   -  The dashboard MVP we can think of as part of the end of User Auth where we get the landing page after logging in
   -  Split up MVPs in this way:
   
   - Servers
   - Channels within servers
   - Live Chat
   - Direct Messaging via private servers
   
   - bullet points in MVPs look good!

Schema
   
   -  This might be an older version of your schema, all 3 tables are the same. Refactor and let me know when you're ready!

Great work!

**Comment by rlim92** [comment]
Hey Daniel!

### Schema
- [ ] we'll need an idea of who can access each server so create a joins table between users and servers that indicate membership to those servers
- [ ] We'll need a `messages` table as well, make sure to add that!
